#!/bin/bash
# generate_client_config.sh
#
# Builds one swanctl directory per test client in ${CONFIG_DIR}/<client>.
# Each client container points SWANCTL_DIR at its own directory. The tunnel
# is not started automatically - the e2e tests initiate it explicitly.

set -euo pipefail
cd "$(dirname "$0")"
source ./versions.sh

CONFIG_DIR="${CONFIG_DIR:-/config}"
PKI="${CONFIG_DIR}/pki"

for client in "${CLIENT_IMAGE_VERSIONS[@]}"; do
    DIR="${CONFIG_DIR}/${client}"

    mkdir -p "$DIR/x509" "$DIR/x509ca" "$DIR/private"
    cp "$PKI/ca.crt" "$DIR/x509ca/ca.crt"
    cp "$PKI/${client}.crt" "$DIR/x509/${client}.crt"
    cp "$PKI/${client}.key" "$DIR/private/${client}.key"
    chmod 0700 "$DIR/private"
    chmod 0600 "$DIR/private/${client}.key"

    # encap = yes forces UDP encapsulation (port 4500), which passes Docker
    # bridges reliably unlike raw ESP.
    cat > "$DIR/swanctl.conf" << EOF
# Generated by generate_client_config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

connections {
    home {
        version = 2
        remote_addrs = ${SERVER_EXTERNAL_IP}
        proposals = ${IKE_PROPOSALS}
        vips = 0.0.0.0
        encap = yes

        local {
            auth = pubkey
            certs = ${client}.crt
            id = ${client}.strongswan.com
        }
        remote {
            auth = pubkey
            id = ${SERVER_ID}
        }
        children {
            protected {
                remote_ts = ${INTERNAL_NETWORK}
                esp_proposals = ${ESP_PROPOSALS}
            }
        }
    }
}
EOF

    echo "✓ Client configuration for ${client} written to $DIR"
done
