#!/bin/bash
# generate_server_config.sh
#
# Builds the server's swanctl directory in ${CONFIG_DIR}/server. The server
# container points SWANCTL_DIR at it. Road-warrior setup: clients
# authenticate with certificates, get a virtual IP from ${VPN_POOL} and reach
# ${INTERNAL_NETWORK} through the tunnel.

set -euo pipefail
cd "$(dirname "$0")"
source ./versions.sh

CONFIG_DIR="${CONFIG_DIR:-/config}"
PKI="${CONFIG_DIR}/pki"
DIR="${CONFIG_DIR}/server"

mkdir -p "$DIR/x509" "$DIR/x509ca" "$DIR/private"
cp "$PKI/ca.crt" "$DIR/x509ca/ca.crt"
cp "$PKI/server.crt" "$DIR/x509/server.crt"
cp "$PKI/server.key" "$DIR/private/server.key"
chmod 0700 "$DIR/private"
chmod 0600 "$DIR/private/server.key"

cat > "$DIR/swanctl.conf" << EOF
# Generated by generate_server_config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

connections {
    rw {
        version = 2
        proposals = ${IKE_PROPOSALS}
        pools = rw_pool
        send_cert = always
        unique = never

        local {
            auth = pubkey
            certs = server.crt
            id = ${SERVER_ID}
        }
        remote {
            auth = pubkey
            cacerts = ca.crt
        }
        children {
            protected {
                local_ts = ${INTERNAL_NETWORK}
                esp_proposals = ${ESP_PROPOSALS}
                dpd_action = clear
            }
        }
    }
}

pools {
    rw_pool {
        addrs = ${VPN_POOL}
    }
}
EOF

echo "✓ Server configuration written to $DIR"
cat "$DIR/swanctl.conf"
